### ISSUE TITLE
Example for docker-compose on https://hub.docker.com/_/yourls/ not working

### ISSUE THREAD

**Issue by MarcProe** [YOURLS/docker-yourls#13]
The example stack.yml file does not work. You need to give alle env vars, as they do not seem to switch to default. Here's a working example:

```
version: '3.1'

services:

  yourls:
    image: yourls
    restart: always
    ports:
      - 8080:80
    environment:
      YOURLS_DB_HOST: mysql
      YOURLS_DB_USER: root
      YOURLS_DB_PASS: example
      YOURLS_DB_NAME: yourls
      YOURLS_SITE: https://example.com

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_HOST: '%'
```
