### ISSUE TITLE
Integrate yourls plugins to docker image

### ISSUE THREAD

**Issue by moookino** [YOURLS/docker-yourls#16]
Hi, is it possible to easily add plugins to existing docker image builds? 
E.g. by providing some related path and config envs for plugins in docker-compose

Thanks in advance! 
M.

**Comment by LeoColomb** [comment]
@moookino Sure, you can definitely add a volume pointing the `user/plugins/` folder!

```bash
docker run --name some-yourls -p 8080:80 -v /local/folder:/var/www/html/user/plugins -d yourls
```

```yaml
version: '3.1'

services:

  yourls:
    image: yourls
    restart: always
    ports:
      - 8080:80
    environment:
      YOURLS_DB_PASS: example
      YOURLS_SITE: https://example.com
    volumes:
      - /local/folder:/var/www/html/user/plugin

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
```

Let me know if it's working for you.
