### ISSUE TITLE
YOURLS failed when using MySQL 8

### ISSUE THREAD

**Issue by Smankusors** [YOURLS/docker-yourls#50]
* [x] I've read the [guidelines for Contributing to YOURLS Projects](https://github.com/YOURLS/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [YOURLS Discourse](https://discourse.yourls.org/) community

**Describe the bug**
When using MySQL 8, these error message appears when trying to run the docker image.
```
Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 17

Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 17

MySQL Connection Error: (2054) The server requested authentication method unknown to the client
```
It turns out that the image YOURLS uses PHP version 7.2, which the mysql client didn't support `caching_sha2_password` yet. And according to [this stackoverflow](https://stackoverflow.com/questions/50026939/php-mysqli-connect-authentication-method-unknown-to-the-client-caching-sha2-pa), it says that PHP version 7.4 fixes that. And it does fix this when I upgrade it to 7.4. So... time to upgrade the PHP I guess?

The image runs fine however when I'm using MySQL 5.7.

**To Reproduce**
Here just use this docker compose to reproduce
```
version: '3.1'
services:
  yourls:
    image: yourls
    restart: always
    ports:
      - 8000:80
    environment:
      YOURLS_DB_PASS: example
      YOURLS_SITE: http://127.0.0.1:8000
      YOURLS_USER: example_username
      YOURLS_PASS: example_password
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
```

**Expected behavior**
Runs normally

**Actual behavior**
Failed to boot

**Versions**
Tested on these docker image tags :
* 1.7.9
* 1.7.9-fpm

**Additional Context**
If upgrading php 7.4 is fine, I can do pull request if you want 🙂
