### ISSUE TITLE
White screen with 1.8 using docker

### ISSUE THREAD

**Issue by Niduroki** [YOURLS/docker-yourls#65]
**Describe the bug**
White screen with 1.8 using docker.

**To Reproduce**
1) docker-compose file:
```yml
version: '3.1'

services:

  yourls:
    image: yourls:1.8
    restart: always
    ports:
      - 8080:80
    environment:
      YOURLS_DB_PASS: example
      YOURLS_SITE: http://127.0.0.1:8080
      YOURLS_USER: user
      YOURLS_PASS: pass
      YOURLS_DEBUG: "true"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
```
2) `docker-compose -f docker-compose.yml up`
3) Go to http://127.0.0.1:8080/admin, click install, click "YOURLS Administration Page"
4) White screen. Even the debug setting doesn't give any output.
5) Clear cookies, log in again: White screen.

**Versions**
Docker Image [1.8-apache](https://hub.docker.com/layers/yourls/library/yourls/apache/images/sha256-0fc7a6c066246be445ea82cf3abd699696491e8d1815729c49dca4515fe0087d?context=explore)

```
$ docker system info
…
 Server Version: 20.10.3
…
 Kernel Version: 5.10.16-arch1-1
 Operating System: Arch Linux
…
```
Same problem also appears to happen on my server:
```
$ docker system info
…
 Server Version: 19.03.13
…
 Kernel Version: 5.10.16-200.fc33.x86_64
 Operating System: Fedora 33 (Thirty Three)
…
```

**Additional context**
It's something to do with the authentication. If you add `YOURLS_PRIVATE: "false"` to the yourls environment variables everything works as expected (without password-protection, that is).

----

Is this maybe a docker problem to report over at https://github.com/YOURLS/docker-yourls ?
