### ISSUE TITLE
It seems something wrong with your demo yml configs ?

### ISSUE THREAD

**Issue by dingjianhub** [YOURLS/docker-yourls#80]
* [x] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [x] This request isn't a duplicate of an existing issue, opened or closed
* [x] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [x] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions)

**Describe the bug**

I use your docker images and docker-compose to start yourls app. I just copy your yml cofings then to start it. But the logs tell me  `MySQL Connection Error: (1045) Access denied for user 'root'@'172.19.0.2' (using password: YES) ` , is there some thing wrong with your demo configs?

```
version: "3.1"

services:
  yourls:
    image: yourls
    restart: always
    ports:
      - 53080:80
    environment:
      YOURLS_DB_PASS: dfwHGud736H
      YOURLS_SITE: https://dwz.xxxxx.com
      YOURLS_USER: fdey273Hueb
      YOURLS_PASS: 284hdY2fe892

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: djwu28w36svsyw82gs7

```

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Versions**
You can get this information from referencing `CHANGELOG.md` or the releases page.
Also, please include:
* The OS and what version of the OS you're running.
* Plugins or extensions activated if applicable.

**Additional context**
