### ISSUE TITLE
Docker setup doesn't work at all

### ISSUE THREAD

**Issue by arladmin** [YOURLS/docker-yourls#88]
* [x] I've read the [Troubleshooting First Steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps)
* [X] This request isn't a duplicate of an existing issue, opened or closed
* [X] I've read the [docs](https://yourls.org/) and followed them (if applicable)
* [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions)

**Describe the bug**
Trying to start YOURLS with a docker setup doesn't work
![image](https://user-images.githubusercontent.com/64059154/122671981-dae42480-d1e6-11eb-86ec-a21eda32ce57.png)

**To Reproduce**
docker-compose.yml:
```
version: '3.1'

services:

    yourls:
        image: yourls
        restart: always
        ports:
        - 9080:80
        environment:
            YOURLS_DB_NAME: mysql
            YOURLS_DB_PASS: password
            YOURLS_SITE: http://localhost:9080
            YOURLS_USER: admin
            YOURLS_PASS: admin_password
            YOURLS_DEBUG: "true"
            YOURLS_PRIVATE: "false"
        depends_on: 
            - mysql
 
    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
```

**Expected behavior**
It should work normally

**Actual behavior**
```
Attaching to yourls_yourls_1, yourls_mysql_1

mysql_1 | 2021-06-20 11:11:08+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.

mysql_1 | 2021-06-20 11:11:08+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'

mysql_1 | 2021-06-20 11:11:08+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.25-1debian10 started.

mysql_1 | 2021-06-20 11:11:08+00:00 [Note] [Entrypoint]: Initializing database files


mysql_1 | 2021-06-20T11:11:08.607771Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.25) initializing of server in progress as process 43

mysql_1 | 2021-06-20T11:11:08.615887Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.


yourls_1 |

yourls_1 | Warning: Undefined array key 1 in Standard input code on line 8

yourls_1 |

yourls_1 | Warning: mysqli::__construct(): (HY000/2002): Connection refused in Standard input code on line 17
```

**Versions**
Docker v20.10.7
